#!/usr/bin/env python3
"""Build a text_overrides mod that blanks every VOICED line.

Drop the output in gamedata/load/text_overrides/ (or merge it into
gamedata/load/text_overrides.txt) to play with no subtitles on voiced dialogue
while keeping every other piece of text on screen.

Which lines are voiced is not a guess. A voiced line carries the ~J0(seconds)
command, which exists to pace the scene to its audio clip, so the game itself
marks every line it has a recording for. Dub releases blank exactly these and
keep the timing command; this produces the same result through the mod system.

That test is also what protects the rest. Examine text, item and door prompts,
notes, memos and the cutscene lines Harry has no recording for carry no ~J0 and
get no entry here, so nothing needs to know who is speaking.

Empty value = blank the line. lang_text.c's TextOverrideBuild keeps the
message's own leading ~command prefix and appends " ~E ", so an empty
replacement still comes out voice-synced. It captures only the FIRST command
though, so a line that leads with something else (three do, all ~D) would lose
its ~J0; those get the timing written back explicitly as the replacement text.

    python make_nosubs_override.py [--out <path>]
"""

import argparse
import io
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, "SilentHill_EN_raw.json")

CMD = re.compile(r"~([A-Za-z])([0-9]*)(\([^)]*\))?")


def leading_prefix(orig):
    """What TextOverrideBuild will keep from `orig`. Mirrors lang_text.c: one
    command, its parameters, its (..) group, then following whitespace."""
    if not orig.startswith("~") or len(orig) < 2:
        return ""
    i = 2  # '~' + code letter
    while i < len(orig) and orig[i] not in "( \t~":
        i += 1
    if i < len(orig) and orig[i] == "(":
        while i < len(orig) and orig[i] != ")":
            i += 1
        if i < len(orig):
            i += 1
    while i < len(orig) and orig[i] in " \t":
        i += 1
    return orig[:i]


def voiced_timing(orig):
    """The ~J0(..) command on this line, as written."""
    m = re.search(r"~J0(\([^)]*\))?", orig)
    return m.group(0) if m else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(HERE, "nosubs_text_override.txt"))
    args = ap.parse_args()

    raw = json.load(io.open(RAW, encoding="utf-8"))

    rows = []
    for key, val in sorted(raw.items()):
        if not isinstance(val, str) or "~J0" not in val:
            continue
        if not key.upper().startswith("MAP"):
            continue  # only map messages have a map.idx key

        timing = voiced_timing(val)
        # An empty replacement is enough when the kept prefix already carries
        # the timing; otherwise write the timing back as the replacement.
        replacement = "" if "~J0" in leading_prefix(val) else timing
        rows.append((key.lower(), replacement, val))

    by_map = {}
    for key, replacement, orig in rows:
        by_map.setdefault(key.rsplit(".", 1)[0], []).append((key, replacement, orig))

    with io.open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Silent Hill PC port - no subtitles on voiced lines\n")
        f.write("#\n")
        f.write("# Drop this in gamedata/load/text_overrides/ (any filename), or paste it\n")
        f.write("# into gamedata/load/text_overrides.txt.\n")
        f.write("#\n")
        f.write("# Blanks only the lines the game has a recording for: those carry a\n")
        f.write("# ~J0(seconds) command that paces the scene to its clip, and the port keeps\n")
        f.write("# that command, so scenes run their original length with no text. Examine\n")
        f.write("# text, item and door prompts, notes, and the cutscene lines Harry has no\n")
        f.write("# recording for are not listed here and are unaffected.\n")
        f.write("#\n")
        f.write("# Generated by pc_port/localization/make_nosubs_override.py\n")
        f.write("# %d voiced lines across %d maps.\n" % (len(rows), len(by_map)))

        explicit = 0
        for mapname in sorted(by_map):
            f.write("\n# %s\n" % mapname)
            for key, replacement, orig in by_map[mapname]:
                if replacement:
                    explicit += 1
                    f.write("# leads with another command, so its timing is written back\n")
                f.write("%s = %s\n" % (key, replacement))

    print("wrote %s" % args.out)
    print("  %d voiced lines, %d maps" % (len(rows), len(by_map)))
    print("  %d needed their timing written back explicitly" % explicit)


if __name__ == "__main__":
    main()
